"""empty message

Revision ID: 2da5ffc35cb0
Revises: 05f88cb62395
Create Date: 2017-11-29 17:58:32.907772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2da5ffc35cb0'
down_revision = '05f88cb62395'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('isclosed', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'isclosed')
    # ### end Alembic commands ###
