"""empty message

Revision ID: 4bef3177e17c
Revises: ebccccebee7c
Create Date: 2017-11-27 19:05:38.834115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bef3177e17c'
down_revision = 'ebccccebee7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('imgpath', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'imgpath')
    # ### end Alembic commands ###
