"""empty message

Revision ID: cce7ee363535
Revises: 45ada54467e4
Create Date: 2017-12-02 15:28:46.732783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cce7ee363535'
down_revision = '45ada54467e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('authority', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'authority')
    # ### end Alembic commands ###
